#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=shootervm
MANUFACTURER=htc

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/3D_calibration ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/3D_calibration_main ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/charging ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/htcbatt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/logcat2 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/load-modem.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/mpdecision ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/netmgrd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/qmuxd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/rmt_storage ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/sound8x60 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/thermald ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_imx074_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_imx074_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_imx105_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_imx105_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9e013_ar.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9e013_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9e013_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9p012_ar.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9p012_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9p012_km_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9p012_km_preview.so/ ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9p012_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9t013_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_mt9t013_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_ov8810_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_ov8810_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_ov9726_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_ov9726_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_qs_s5k4e1_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_qs_s5k4e1_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3e2fx_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3e2fx_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3h1gx_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3h1gx_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3h2yx_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k3h2yx_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k4e1gx_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_s5k4e1gx_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_sn12m0pz_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_sn12m0pz_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_vb6801_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_vb6801_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_vx6953_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libchromatix_vx6953_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/drmserver ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/DxDrmServerIpc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/etc/DxDrmConfig_Server.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/etc/permissions/com.google.widevine.software.drm.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/framework/com.google.widevine.software.drm.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdivxdrmdecrypt.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdrm1.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdrm1_jni.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdrmframework.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdrmframework_jni.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libDxDrmCAPI.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libDxDrmJava.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/liboma-drm1-fs.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libwvdrm_L3.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/drm/libdrmwvmplugin.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/drm/libhtcomaplugin.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/dmagent ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/getWiMAXPropDaemond ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/sequansd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/setWiMAXPropDaemond ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/setWiMAXPropDaemond.mod.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxAddRoute ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimax_baud_hack.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxConfigInterface ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDaemon ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDhcpRelease ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDhcpRenew ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDumpKmsg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDumpLastKmsg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxDumpLogcat ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimaxFactoryReset ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/wimax_mtd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/etc/wimax/dhcp/wimaxDhcp.conf ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/etc/wimax/sequansd/DefaultTree.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/etc/wimax/sequansd/sequansd_app.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libcrypto.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdmtree.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libhtcdm.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/framework/wimax.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/hw/camera.default.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/hw/sensors.shooter.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libaudioalsa.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libaudcal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libacdbmapper.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libC2D2.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libcamerapp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libcameraSP.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libcameraface.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdll.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdiag.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libidl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdsi_netctrl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libdsutils.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libgemini.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libgemini2.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/eglsubAndroid.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libgsl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libsc-a2xx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libhtc_acoustic.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libhtc_ril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libhtc_ril_switch.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmmipl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmmmpo.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmmjpeg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmmjps.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmmjpeg2.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmm-color-convertor.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmm-omxcore.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmpl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmllite.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libmlplatform.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libnetmgr.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/liboemcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libOlaEngine.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libOpenMAXAL.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libOpenVG.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libposteffect.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libqc-opt.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libqmi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libqdp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libqmiservices.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/lib/libv8.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/camera.default.so:obj/lib/hw/camera.default.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so


PRODUCT_COPY_FILES += \
    vendor/htc/shootervm/proprietary/camera.default.so:obj/lib/hw/camera.default.so \
    vendor/htc/shootervm/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shootervm/proprietary/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shootervm/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so

# All the blobs necessary for vivow
PRODUCT_COPY_FILES += \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/3D_calibration:/system/bin/3D_calibration \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/3D_calibration_main:/system/bin/3D_calibration_main \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/charging:/system/bin/charging \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/htcbatt:/system/bin/htcbatt \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/logcat2:/system/bin/logcat2 \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/load-modem.sh:/system/bin/load-modem.sh \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/mpdecision:/system/bin/mpdecision \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/netmgrd:/system/bin/netmgrd \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/qmuxd:/system/bin/qmuxd \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/rmt_storage:/system/bin/rmt_storage \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/sound8x60:/system/bin/sound8x60 \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/thermald:/system/bin/thermald \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_imx074_default_video.so:/system/lib/libchromatix_imx074_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_imx074_preview.so:/system/lib/libchromatix_imx074_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_imx105_default_video.so:/system/lib/libchromatix_imx105_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_imx105_preview.so:/system/lib/libchromatix_imx105_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9e013_ar.so:/system/lib/libchromatix_mt9e013_ar.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9e013_default_video.so:/system/lib/libchromatix_mt9e013_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9e013_preview.so:/system/lib/libchromatix_mt9e013_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9p012_ar.so:/system/lib/libchromatix_mt9p012_ar.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9p012_default_video.so:/system/lib/libchromatix_mt9p012_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9p012_km_default_video.so:/system/lib/libchromatix_mt9p012_km_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9p012_km_preview.so:/system/lib/libchromatix_mt9p012_km_preview.so/ \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9p012_preview.so:/system/lib/libchromatix_mt9p012_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9t013_default_video.so:/system/lib/libchromatix_mt9t013_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_mt9t013_preview.so:/system/lib/libchromatix_mt9t013_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov8810_default_video.so:/system/lib/libchromatix_ov8810_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov8810_preview.so:/system/lib/libchromatix_ov8810_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov9726_preview.so:/system/lib/libchromatix_ov9726_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov9726_video.so:/system/lib/libchromatix_ov9726_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_qs_s5k4e1_preview.so:/system/lib/libchromatix_qs_s5k4e1_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_qs_s5k4e1_video.so:/system/lib/libchromatix_qs_s5k4e1_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3e2fx_default_video.so:/system/lib/libchromatix_s5k3e2fx_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3e2fx_preview.so:/system/lib/libchromatix_s5k3e2fx_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3h1gx_default_video.so:/system/lib/libchromatix_s5k3h1gx_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3h1gx_preview.so:/system/lib/libchromatix_s5k3h1gx_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k4e1gx_default_video.so:/system/lib/libchromatix_s5k4e1gx_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_s5k4e1gx_preview.so:/system/lib/libchromatix_s5k4e1gx_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_sn12m0pz_default_video.so:/system/lib/libchromatix_sn12m0pz_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_sn12m0pz_preview.so:/system/lib/libchromatix_sn12m0pz_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_vb6801_default_video.so:/system/lib/libchromatix_vb6801_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_vb6801_preview.so:/system/lib/libchromatix_vb6801_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_vx6953_default_video.so:/system/lib/libchromatix_vx6953_default_video.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_vx6953_preview.so:/system/lib/libchromatix_vx6953_preview.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/drmserver:/system/bin/drmserver \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/DxDrmServerIpc:/system/bin/DxDrmServerIpc \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/DxDrmConfig_Server.txt:/system/etc/DxDrmConfig_Server.txt \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/com.google.widevine.software.drm.xml:/system/etc/permissions/com.google.widevine.software.drm.xml \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/com.google.widevine.software.drm.jar:/system/framework/com.google.widevine.software.drm.jar \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdivxdrmdecrypt.so:/system/lib/libdivxdrmdecrypt.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrm1.so:/system/lib/libdrm1.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrm1_jni.so:/system/lib/libdrm1_jni.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmframework.so:/system/lib/libdrmframework.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmframework_jni.so:/system/lib/libdrmframework_jni.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libDxDrmCAPI.so:/system/lib/libDxDrmCAPI.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libDxDrmJava.so:/system/lib/libDxDrmJava.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/liboma-drm1-fs.so:/system/lib/liboma-drm1-fs.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libwvdrm_L3.so:/system/lib/libwvdrm_L3.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmwvmplugin.so:/system/lib/drm/libdrmwvmplugin.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libhtcomaplugin.so:/system/lib/drm/libhtcomaplugin.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/dmagent:/system/bin/dmagent \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/sequansd:/system/bin/sequansd \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/setWiMAXPropDaemond.mod.so:/system/bin/setWiMAXPropDaemond.mod.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxAddRoute:/system/bin/wimaxAddRoute \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimax_baud_hack.so:/system/bin/wimax_baud_hack.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxConfigInterface:/system/bin/wimaxConfigInterface \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDaemon:/system/bin/wimaxDaemon \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDhcpRelease:/system/bin/wimaxDhcpRelease \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDhcpRenew:/system/bin/wimaxDhcpRenew \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDumpKmsg:/system/bin/wimaxDumpKmsg \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDumpLastKmsg:/system/bin/wimaxDumpLastKmsg \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDumpLogcat:/system/bin/wimaxDumpLogcat \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxFactoryReset:/system/bin/wimaxFactoryReset \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimax_mtd:/system/bin/wimax_mtd \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimaxDhcp.conf:/system/etc/wimax/dhcp/wimaxDhcp.conf \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/DefaultTree.xml:/system/etc/wimax/sequansd/DefaultTree.xml \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/sequansd_app.xml:/system/etc/wimax/sequansd/sequansd_app.xml \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcrypto.so:/system/lib/libcrypto.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdmtree.so:/system/lib/libdmtree.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libhtcdm.so:/system/lib/libhtcdm.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/wimax.jar:/system/framework/wimax.jar \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/camera.default.so:/system/lib/hw/camera.default.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors.shooter.so:/system/lib/hw/sensors.shooter.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudcal.so:/system/lib/libaudcal.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libacdbmapper.so:/system/lib/libacdbmapper.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libC2D2.so:/system/lib/libC2D2.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamerapp.so:/system/lib/libcamerapp.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcameraSP.so:/system/lib/libcameraSP.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcameraface.so:/system/lib/libcameraface.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdll.so:/system/lib/libdll.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdiag.so:/system/lib/libdiag.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libidl.so:/system/lib/libidl.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsutils.so:/system/lib/libdsutils.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgemini.so:/system/lib/libgemini.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgemini2.so:/system/lib/libgemini2.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgsl.so:/system/lib/libgsl.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmipl.so:/system/lib/libmmipl.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmmpo.so:/system/lib/libmmmpo.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmjps.so:/system/lib/libmmjps.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmjpeg2.so:/system/lib/libmmjpeg2.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmm-omxcore.so:/system/lib/libmm-omxcore.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmpl.so:/system/lib/libmpl.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmllite.so:/system/lib/libmllite.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOlaEngine.so:/system/lib/libOlaEngine.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libposteffect.so:/system/lib/libposteffect.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqc-opt.so:/system/lib/libqc-opt.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi.so:/system/lib/libqmi.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqdp.so:/system/lib/libqdp.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \\
vendor/__MANUFACTURER__/__DEVICE__/proprietary/libv8.so:/system/lib/libv8.so \\

EOF

sh setup-makefiles.sh
